matrix:
  VERSION:
    - "4.2.6"
    - "5.5.0"

publish:
  docker:
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/node
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
    build_args: "NODE_VERSION=$$VERSION"
